<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDZwPx2L\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDZwPx2L/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDZwPx2L.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDZwPx2L\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerDZwPx2L\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'DZwPx2L',
    'container.build_id' => '6d770712',
    'container.build_time' => 1522078050,
));
