version: '3'
services:
    php-fpm:
        build: docker/php-fpm
        container_name: php-fpm_container
        volumes:
            - ./project:/var/www
            - ./logs/app:/var/log/default
            - ~/.composer:/root/.composer
            - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
        links:
            - mariadb
    nginx:
        build: docker/nginx
        container_name: nginx_container
        ports:
            - 80:80
        links:
            - php-fpm
        volumes:
            - ./project:/var/www
            - ./logs/nginx:/var/log/nginx
    mariadb:
        build: docker/mariadb
        container_name: mariadb_container
        volumes:
            - ./data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root